rules:
- path: Models/
  pattern: \[a-zA-z0-9_-\[\\+\]\]*Model.swift
  uppercasePrefix: true
  severity: error
  against: false
  ignores:
    -
excludes:
  - .build
  - .git
  - .xcworkspace
  - .xcodeproj
  - .
  - ..
  - Pods
  - Carthage
