base_pattern: \[a-zA-z0-9_-\[\\+\]\]*
rules:
  - path: Models/
    pattern: Model.swift
    severity: error
    relative_to_base: true
    ignores:
      -
excludes:
  - .build
  - .git
  - .xcworkspace
  - .xcodeproj
  - .
  - ..
  - Pods
  - Carthage
